/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:window1:351197:
  appc.background(230);
} //_CODE_:window1:351197:

public void option4_clicked1(GOption source, GEvent event) { //_CODE_:option4:922328:
  println("option4 - GOption event occured " + System.currentTimeMillis()%10000000 );
  mode = 0;
     delay(100); 
    myPort.write(0xFF);
    delay(100);
    myPort.write(0);
        delay(100);
    myPort.write(0xFE);
        delay(100);
    myPort.write(0);
        delay(100);
    myPort.write(0xFD);
        delay(100);
    myPort.write(0);
        delay(100);
} //_CODE_:option4:922328:

public void option5_clicked1(GOption source, GEvent event) { //_CODE_:option5:292475:
  println("option5 - GOption event occured " + System.currentTimeMillis()%10000000 );
  mode = 1;
} //_CODE_:option5:292475:

public void option6_clicked1(GOption source, GEvent event) { //_CODE_:option6:459970:
  println("option6 - GOption event occured " + System.currentTimeMillis()%10000000 );
  mode = 2;
} //_CODE_:option6:459970:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:496389:
  println("slider4 - GSlider event occured " + System.currentTimeMillis()%10000000 );
  if (mode==2){
  myPort.write(0xFF);
  myPort.write((byte)source.getValueI());
  }else{
   rMax =  source.getValueI();
  }
} //_CODE_:slider4:496389:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:515781:
  println("slider1 - GSlider event occured " + System.currentTimeMillis()%10000000 );
    if (mode==2){
  myPort.write(0xFE);
  myPort.write((byte)source.getValueI());
    }else{
   gMax =  source.getValueI();
  }
} //_CODE_:slider1:515781:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:809869:
  println("slider2 - GSlider event occured " + System.currentTimeMillis()%10000000 );
    if (mode==2){
  myPort.write(0xFD);
  myPort.write((byte)source.getValueI());
    }else{
   bMax =  source.getValueI();
  }
} //_CODE_:slider2:809869:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  window1 = new GWindow(this, "Window title", 0, 0, 320, 130, false, JAVA2D);
  window1.addDrawHandler(this, "win_draw1");
  togGroup2 = new GToggleGroup();
  option4 = new GOption(window1.papplet, 10, 10, 50, 20);
  option4.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option4.setText("Off");
  option4.setOpaque(false);
  option4.addEventHandler(this, "option4_clicked1");
  option5 = new GOption(window1.papplet, 60, 10, 60, 20);
  option5.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option5.setText("Music");
  option5.setOpaque(false);
  option5.addEventHandler(this, "option5_clicked1");
  option6 = new GOption(window1.papplet, 120, 10, 60, 20);
  option6.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  option6.setText("Manual");
  option6.setOpaque(false);
  option6.addEventHandler(this, "option6_clicked1");
  togGroup2.addControl(option4);
  option4.setSelected(true);
  togGroup2.addControl(option5);
  togGroup2.addControl(option6);
  label4 = new GLabel(window1.papplet, 10, 30, 50, 30);
  label4.setText("Red:");
  label4.setOpaque(false);
  slider4 = new GSlider(window1.papplet, 60, 30, 250, 30, 10.0);
  slider4.setLimits(128, 0, 255);
  slider4.setNumberFormat(G4P.INTEGER, 0);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  label1 = new GLabel(window1.papplet, 10, 60, 50, 30);
  label1.setText("Green:");
  label1.setOpaque(false);
  slider1 = new GSlider(window1.papplet, 60, 60, 250, 30, 10.0);
  slider1.setLimits(128, 0, 255);
  slider1.setNumberFormat(G4P.INTEGER, 0);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  label2 = new GLabel(window1.papplet, 10, 90, 50, 30);
  label2.setText("Blue:");
  label2.setOpaque(false);
  slider2 = new GSlider(window1.papplet, 60, 90, 250, 30, 10.0);
  slider2.setLimits(128, 0, 255);
  slider2.setNumberFormat(G4P.INTEGER, 0);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GToggleGroup togGroup2; 
GOption option4; 
GOption option5; 
GOption option6; 
GLabel label4; 
GSlider slider4; 
GLabel label1; 
GSlider slider1; 
GLabel label2; 
GSlider slider2; 

